# Site settings
title: Ana Paula Mendes
description: "A tech blog to share about my career"
baseurl: ""
url: ""

# User settings
username: ANA PAULA MENDES
occupation: Senior Software Engineer
user_title: Ana Paula Mendes
email: anapaula.ds.mendes@gmail.com
github_username:  anapaulamendes
linkedin_public_url: anapauladsmendes/
youtube_channel: ananoterminal
disqus_username: ananoterminal
profile_picture: https://avatars0.githubusercontent.com/u/9610091?s=460&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', Gemfile, Gemfile.lock]
